//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppoiment
    {
        public tblAppoiment()
        {
            this.tblOfficeVisits = new HashSet<tblOfficeVisit>();
        }
    
        public long AppoinmentNo { get; set; }
        public System.DateTime Date { get; set; }
        public bool Status { get; set; }
        public long PatientId { get; set; }
        public long DoctorAssigned { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual ICollection<tblOfficeVisit> tblOfficeVisits { get; set; }
        public virtual tblPatient tblPatient { get; set; }
    }
}
