//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctorType
    {
        public tblDoctorType()
        {
            this.tblDoctors = new HashSet<tblDoctor>();
        }
    
        public int TypeId { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<tblDoctor> tblDoctors { get; set; }
    }
}
