//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctor
    {
        public tblDoctor()
        {
            this.tblAppoiments = new HashSet<tblAppoiment>();
            this.tblProcedures = new HashSet<tblProcedure>();
        }
    
        public long StaffId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public decimal HourlyRate { get; set; }
        public long UserId { get; set; }
        public string Specialization { get; set; }
        public int DoctorTypeId { get; set; }
    
        public virtual ICollection<tblAppoiment> tblAppoiments { get; set; }
        public virtual ICollection<tblProcedure> tblProcedures { get; set; }
        public virtual tblDoctorType tblDoctorType { get; set; }
        public virtual tblLogin tblLogin { get; set; }
    }
}
