//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public long EmployeeId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public long LoginId { get; set; }
    
        public virtual tblLogin tblLogin { get; set; }
    }
}
