//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInsurance
    {
        public long PolicyNo { get; set; }
        public string CompanyName { get; set; }
        public Nullable<long> Telephone { get; set; }
        public int ContractPrecentage { get; set; }
        public long PatientId { get; set; }
    
        public virtual tblPatient tblPatient { get; set; }
    }
}
