//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogin
    {
        public tblLogin()
        {
            this.tblDoctors = new HashSet<tblDoctor>();
            this.tblEmployees = new HashSet<tblEmployee>();
        }
    
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int UserTypeId { get; set; }
    
        public virtual ICollection<tblDoctor> tblDoctors { get; set; }
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
        public virtual tblUserType tblUserType { get; set; }
    }
}
