//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatient
    {
        public tblPatient()
        {
            this.tblAppoiments = new HashSet<tblAppoiment>();
            this.tblInsurances = new HashSet<tblInsurance>();
            this.tblOfficeVisits = new HashSet<tblOfficeVisit>();
        }
    
        public long PatientId { get; set; }
        public string PatientName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> FirstVisit { get; set; }
    
        public virtual ICollection<tblAppoiment> tblAppoiments { get; set; }
        public virtual ICollection<tblInsurance> tblInsurances { get; set; }
        public virtual ICollection<tblOfficeVisit> tblOfficeVisits { get; set; }
    }
}
