//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserType
    {
        public tblUserType()
        {
            this.tblLogins = new HashSet<tblLogin>();
        }
    
        public int UserTypeId { get; set; }
        public string UserType { get; set; }
    
        public virtual ICollection<tblLogin> tblLogins { get; set; }
    }
}
